REPORT ZTESTE_INCLUDE.

DATA: lv_resultado TYPE p DECIMALS 2,
      lv_operacao TYPE string.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE text-001.

  PARAMETERS: p_input1 TYPE p DECIMALS 2,
              p_input2 TYPE p DECIMALS 2.

SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE text-002.

PARAMETERS: r1 RADIOBUTTON GROUP g1,
            r2 RADIOBUTTON GROUP g1,
            r3 RADIOBUTTON GROUP g1,
            r4 RADIOBUTTON GROUP g1.

SELECTION-SCREEN END OF BLOCK b2.


INCLUDE ZCALCULA2.
